---
- hosts: all
  pre_tasks:
      - name: Set new value for variable
        set_fact:
          new_project: "{{ projectStatus }}"
        when: (projectStatus == 'false') or (projectStatus == 'true')
  tasks:
  - name: Print new_project value
    debug:
      msg: "new_project: {{ new_project }}\nSome text"
- import_playbook: database.yml
- import_playbook: frontend.yml
- import_playbook: backend.yml
- import_playbook: magentotools.yml
- import_playbook: redis.yml
- import_playbook: app.yml
- import_playbook: mailcatcher.yml
#- import_playbook: compozer.yml # old playbook
- import_playbook: new_project.yml
  when: (new_project == true)
- import_playbook: exist_project.yml
  when: (new_project == false)